In [1]:
#Importar llibreria pandas
import pandas as pd

In [2]:
#Importar fitxers CSV (products.csv i orders.csv)
products = pd.read_csv('products.csv')
orders = pd.read_csv('orders.csv')

In [ ]:
#Dades originals del DataFrame 'products'
products

   id         name       cost
0   0  screwdriver   2.981164
1   1       wrench   6.490396
2   2       hammer   2.903732
3   3       sickle   8.901570
4   4       candle   9.806495
5   5      bandsaw  10.435252

In [4]:
#Tipus de dades del DataFrame 'products'
products.dtypes

id        int64
name     object
cost    float64
dtype: object

In [5]:
#Dades originals del DataFrame 'orders'
orders

    id  customer             products
0    0         0              1 0 1 0
1    1        22    0 5 0 4 5 3 2 1 1
2    2        57                5 2 4
3    3        20            4 3 0 2 4
4    4        28          5 0 5 0 3 4
5    5        40              0 1 0 2
6    6        32    5 5 0 5 1 5 1 3 1
7    7         5              5 0 3 2
8    8        45              1 2 1 0
9    9        37            0 5 5 5 2
10  10        38        3 5 0 1 1 5 3
11  11        51            4 1 1 3 2
12  12         6              5 2 1 0
13  13        44        2 0 0 5 1 0 5
14  14        34              1 3 1 5
15  15         3            1 1 5 5 1
16  16        50    0 1 3 5 5 0 0 0 0
17  17        24      4 5 4 1 1 0 5 3
18  18        54            2 0 5 0 3
19  19        59          4 0 4 4 4 5
20  20        36                    4
21  21         8                  4 2
22  22        15    5 4 0 2 1 0 0 0 4
23  23        25                  5 5
24  24        21        2 3 0 4 4 5 4
25  25        34        1 5 0 0 3 3 0
26  26         5  2 0 4 4 5 4 2 1 2 1
27  27        34      5 5 3 3 3 0 3 4
28  28        45                  1 5
29  29        15                    2
30  30        19              5 0 4 5
31  31        41      3 2 3 4 5 1 5 2
32  32        47          5 0 3 0 1 1
33  33        48                  0 2
34  34        46          0 3 1 1 2 3
35  35        44                3 4 5
36  36        38                    5
37  37        32            5 3 1 5 4
38  38        35                  1 4
39  39        29                3 2 1
40  40        44                4 5 2
41  41        24  0 4 3 4 0 3 4 1 3 2
42  42        10    5 5 4 4 1 5 0 0 4
43  43        17      1 4 0 2 1 5 2 3
44  44         9            4 3 1 2 5
45  45        22    0 4 3 5 1 0 4 0 3
46  46        29    2 2 3 3 2 0 2 5 3
47  47         5                  2 1
48  48        44    2 3 0 5 2 2 1 1 2
49  49        58                    1

In [6]:
#Tipus de dades del DataFrame 'orders'
orders.dtypes

id           int64
customer     int64
products    object
dtype: object

In [7]:
#Crear nou DataFrame 'order_prices' amb les columnes 'id' i 'euros'.
order_prices = pd.DataFrame(columns=["id", "euros"])

#Afegir dades 'id' del DataFrame 'orders' a 'order_prices'
#NOTA: 'euros' encara no te cap valor.
order_prices["id"] = orders['id']
order_prices

    id euros
0    0   NaN
1    1   NaN
2    2   NaN
3    3   NaN
4    4   NaN
5    5   NaN
6    6   NaN
7    7   NaN
8    8   NaN
9    9   NaN
10  10   NaN
11  11   NaN
12  12   NaN
13  13   NaN
14  14   NaN
15  15   NaN
16  16   NaN
17  17   NaN
18  18   NaN
19  19   NaN
20  20   NaN
21  21   NaN
22  22   NaN
23  23   NaN
24  24   NaN
25  25   NaN
26  26   NaN
27  27   NaN
28  28   NaN
29  29   NaN
30  30   NaN
31  31   NaN
32  32   NaN
33  33   NaN
34  34   NaN
35  35   NaN
36  36   NaN
37  37   NaN
38  38   NaN
39  39   NaN
40  40   NaN
41  41   NaN
42  42   NaN
43  43   NaN
44  44   NaN
45  45   NaN
46  46   NaN
47  47   NaN
48  48   NaN
49  49   NaN

In [8]:
#Tipus de dades del DataFrame 'order_prices'
order_prices.dtypes

id        int64
euros    object
dtype: object

In [9]:
#Realitzar un split de la columna "products" del DataFrame "orders", per separar els IDs dels productes.
#Fem un DataFrame transposat (50x10 -> 10x50) amb l'opció T per facilitar el merge amb 'products'.
df_transposed = orders['products'].str.split(expand=True).T
df_transposed

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,1,0,5,4,5,0,5,5,1,0,...,4,0,5,1,4,0,2,2,2,1
1,0,5,2,3,0,1,5,0,2,5,...,5,4,5,4,3,4,2,1,3,None
2,1,0,4,0,5,0,0,3,1,5,...,2,3,4,0,1,3,3,None,0,None
3,0,4,None,2,0,2,5,2,0,5,...,None,4,4,2,2,5,3,None,5,None
4,None,5,None,4,3,None,1,None,None,2,...,None,0,1,1,5,1,2,None,2,None
5,None,3,None,None,4,None,5,None,None,None,...,None,3,5,5,None,0,0,None,2,None
6,None,2,None,None,None,None,1,None,None,None,...,None,4,0,2,None,4,2,None,1,None
7,None,1,None,None,None,None,3,None,None,None,...,None,1,0,3,None,0,5,None,1,None
8,None,1,None,None,None,None,1,None,None,None,...,None,3,4,None,None,3,3,None,2,None
9,None,None,None,None,None,None,None,None,None,None,...,None,2,None,None,None,None,None,None,None,None

In [ ]:
#Bucle for per recorrer el DataFrame transposat per columnes
for col in df_transposed:
    #Crear un aux_col amb la columna actual del DataFrame transposat
    aux_col = pd.DataFrame({"id": df_transposed[col]})

    #Convertir els valors de la columna 'aux_col' de string a float64
    aux_col = aux_col.astype('float64')

    #Realitzar un merge amb la columna 'aux_col' del DataFrame transposat amb 'products'
    #La idea es aconseguir el cost del producte que coincideixin amb el ID (on='id').
    #La opció how='inner' ens permet relacionar les columnes d'ambdos DataFrames amb el mateix ID (evitant nuls com faria 'left' i 'right').
    aux_col = pd.merge(aux_col, products, how='inner', on='id')

    #Sumar els costos de la comanda amb sum() i afegir el cost toal en la columna 'euros'.
    order_prices.loc[col, 'euros'] = aux_col['cost'].sum()

order_prices

    id      euros
0    0   18.94312
1    1  61.425421
2    2  23.145479
3    3  34.399455
4    4  45.540896
5    5  15.356456
6    6  73.094931
7    7  25.221718
8    8  18.865689
9    9  37.190652
10  10    54.6356
11  11   34.59259
12  12  22.810544
13  13  39.208124
14  14  32.317615
15  15  40.341694
16  16  51.168289
17  17   65.34702
18  18  28.202881
19  19  52.642395
20  20   9.806495
21  21  12.710227
22  22  51.367025
23  23  20.870504
24  24  54.641202
25  25  43.672279
26  26   64.52789
27  27  69.264442
28  28  16.925649
29  29   2.903732
30  30  33.658163
31  31  60.777999
32  32  38.279942
33  33   5.884896
34  34  36.668828
35  35  29.143317
36  36  10.435252
37  37  46.068965
38  38  16.296891
39  39  18.295698
40  40  23.145479
41  41   71.48065
42  42  73.177965
43  43  50.912738
44  44  38.537445
45  45  63.285269
46  46  51.736054
47  47   9.394129
48  48  46.913707
49  49   6.490396

In [11]:
#Exportar el DataFrame en un fitxer CSV (order_prices.csv)
order_prices.to_csv("order_prices.csv", index=False)