In [15]:
#Importar llibreria pandas
import pandas as pd

In [16]:
#Importar fitxers CSV (customers.csv, orders.csv i order_prices.csv)
customers = pd.read_csv('customers.csv')
orders = pd.read_csv('orders.csv')
order_prices = pd.read_csv('order_prices.csv')

In [17]:
#Dades originals del DataFrame 'customers'
customers

    id firstname    lastname
0    0      John     Maxwell
1    1      John  Heisenberg
2    2      John       Fermi
3    3      John     Feynman
4    4      John   Lavoisier
5    5      John     Pasteur
6    6     James     Maxwell
7    7     James  Heisenberg
8    8     James       Fermi
9    9     James     Feynman
10  10     James   Lavoisier
11  11     James     Pasteur
12  12     Peter     Maxwell
13  13     Peter  Heisenberg
14  14     Peter       Fermi
15  15     Peter     Feynman
16  16     Peter   Lavoisier
17  17     Peter     Pasteur
18  18      Paul     Maxwell
19  19      Paul  Heisenberg
20  20      Paul       Fermi
21  21      Paul     Feynman
22  22      Paul   Lavoisier
23  23      Paul     Pasteur
24  24     Ringo     Maxwell
25  25     Ringo  Heisenberg
26  26     Ringo       Fermi
27  27     Ringo     Feynman
28  28     Ringo   Lavoisier
29  29     Ringo     Pasteur
30  30    Samuel     Maxwell
31  31    Samuel  Heisenberg
32  32    Samuel       Fermi
33  33    Samuel     Feynman
34  34    Samuel   Lavoisier
35  35    Samuel     Pasteur
36  36       Sam     Maxwell
37  37       Sam  Heisenberg
38  38       Sam       Fermi
39  39       Sam     Feynman
40  40       Sam   Lavoisier
41  41       Sam     Pasteur
42  42      Mary     Maxwell
43  43      Mary  Heisenberg
44  44      Mary       Fermi
45  45      Mary     Feynman
46  46      Mary   Lavoisier
47  47      Mary     Pasteur
48  48     Sarah     Maxwell
49  49     Sarah  Heisenberg
50  50     Sarah       Fermi
51  51     Sarah     Feynman
52  52     Sarah   Lavoisier
53  53     Sarah     Pasteur
54  54      Jane     Maxwell
55  55      Jane  Heisenberg
56  56      Jane       Fermi
57  57      Jane     Feynman
58  58      Jane   Lavoisier
59  59      Jane     Pasteur

In [18]:
#Tipus de dades del DataFrame 'customers'
customers.dtypes

id            int64
firstname    object
lastname     object
dtype: object

In [19]:
#Dades originals del DataFrame 'orders'
orders

    id  customer             products
0    0         0              1 0 1 0
1    1        22    0 5 0 4 5 3 2 1 1
2    2        57                5 2 4
3    3        20            4 3 0 2 4
4    4        28          5 0 5 0 3 4
5    5        40              0 1 0 2
6    6        32    5 5 0 5 1 5 1 3 1
7    7         5              5 0 3 2
8    8        45              1 2 1 0
9    9        37            0 5 5 5 2
10  10        38        3 5 0 1 1 5 3
11  11        51            4 1 1 3 2
12  12         6              5 2 1 0
13  13        44        2 0 0 5 1 0 5
14  14        34              1 3 1 5
15  15         3            1 1 5 5 1
16  16        50    0 1 3 5 5 0 0 0 0
17  17        24      4 5 4 1 1 0 5 3
18  18        54            2 0 5 0 3
19  19        59          4 0 4 4 4 5
20  20        36                    4
21  21         8                  4 2
22  22        15    5 4 0 2 1 0 0 0 4
23  23        25                  5 5
24  24        21        2 3 0 4 4 5 4
25  25        34        1 5 0 0 3 3 0
26  26         5  2 0 4 4 5 4 2 1 2 1
27  27        34      5 5 3 3 3 0 3 4
28  28        45                  1 5
29  29        15                    2
30  30        19              5 0 4 5
31  31        41      3 2 3 4 5 1 5 2
32  32        47          5 0 3 0 1 1
33  33        48                  0 2
34  34        46          0 3 1 1 2 3
35  35        44                3 4 5
36  36        38                    5
37  37        32            5 3 1 5 4
38  38        35                  1 4
39  39        29                3 2 1
40  40        44                4 5 2
41  41        24  0 4 3 4 0 3 4 1 3 2
42  42        10    5 5 4 4 1 5 0 0 4
43  43        17      1 4 0 2 1 5 2 3
44  44         9            4 3 1 2 5
45  45        22    0 4 3 5 1 0 4 0 3
46  46        29    2 2 3 3 2 0 2 5 3
47  47         5                  2 1
48  48        44    2 3 0 5 2 2 1 1 2
49  49        58                    1

In [20]:
#Tipus de dades del DataFrame 'orders'
orders.dtypes

id           int64
customer     int64
products    object
dtype: object

In [21]:
#Dades originals del DataFrame 'order_prices' (creat en la Tasca 1)
order_prices

    id      euros
0    0  18.943120
1    1  61.425421
2    2  23.145479
3    3  34.399455
4    4  45.540896
5    5  15.356456
6    6  73.094931
7    7  25.221718
8    8  18.865689
9    9  37.190652
10  10  54.635600
11  11  34.592590
12  12  22.810544
13  13  39.208124
14  14  32.317615
15  15  40.341694
16  16  51.168289
17  17  65.347020
18  18  28.202881
19  19  52.642395
20  20   9.806495
21  21  12.710227
22  22  51.367025
23  23  20.870504
24  24  54.641202
25  25  43.672279
26  26  64.527890
27  27  69.264442
28  28  16.925649
29  29   2.903732
30  30  33.658163
31  31  60.777999
32  32  38.279942
33  33   5.884896
34  34  36.668828
35  35  29.143317
36  36  10.435252
37  37  46.068965
38  38  16.296891
39  39  18.295698
40  40  23.145479
41  41  71.480650
42  42  73.177965
43  43  50.912738
44  44  38.537445
45  45  63.285269
46  46  51.736054
47  47   9.394129
48  48  46.913707
49  49   6.490396

In [22]:
#Tipus de dades del DataFrame 'order_prices'
order_prices.dtypes

id         int64
euros    float64
dtype: object

In [23]:
#Realitzar un merge dels DataFrames 'order_prices' i 'orders'.
#La idea es aconseguir les columnes de 'orders' coincidint amb el ID (on='id').
#La opció how='inner' ens permet relacionar les columnes d'ambdos DataFrames amb el mateix ID (evitant nuls com faria 'left' i 'right').
df_merged = pd.merge(order_prices, orders, how='inner', on='id')
df_merged

    id      euros  customer             products
0    0  18.943120         0              1 0 1 0
1    1  61.425421        22    0 5 0 4 5 3 2 1 1
2    2  23.145479        57                5 2 4
3    3  34.399455        20            4 3 0 2 4
4    4  45.540896        28          5 0 5 0 3 4
5    5  15.356456        40              0 1 0 2
6    6  73.094931        32    5 5 0 5 1 5 1 3 1
7    7  25.221718         5              5 0 3 2
8    8  18.865689        45              1 2 1 0
9    9  37.190652        37            0 5 5 5 2
10  10  54.635600        38        3 5 0 1 1 5 3
11  11  34.592590        51            4 1 1 3 2
12  12  22.810544         6              5 2 1 0
13  13  39.208124        44        2 0 0 5 1 0 5
14  14  32.317615        34              1 3 1 5
15  15  40.341694         3            1 1 5 5 1
16  16  51.168289        50    0 1 3 5 5 0 0 0 0
17  17  65.347020        24      4 5 4 1 1 0 5 3
18  18  28.202881        54            2 0 5 0 3
19  19  52.642395        59          4 0 4 4 4 5
20  20   9.806495        36                    4
21  21  12.710227         8                  4 2
22  22  51.367025        15    5 4 0 2 1 0 0 0 4
23  23  20.870504        25                  5 5
24  24  54.641202        21        2 3 0 4 4 5 4
25  25  43.672279        34        1 5 0 0 3 3 0
26  26  64.527890         5  2 0 4 4 5 4 2 1 2 1
27  27  69.264442        34      5 5 3 3 3 0 3 4
28  28  16.925649        45                  1 5
29  29   2.903732        15                    2
30  30  33.658163        19              5 0 4 5
31  31  60.777999        41      3 2 3 4 5 1 5 2
32  32  38.279942        47          5 0 3 0 1 1
33  33   5.884896        48                  0 2
34  34  36.668828        46          0 3 1 1 2 3
35  35  29.143317        44                3 4 5
36  36  10.435252        38                    5
37  37  46.068965        32            5 3 1 5 4
38  38  16.296891        35                  1 4
39  39  18.295698        29                3 2 1
40  40  23.145479        44                4 5 2
41  41  71.480650        24  0 4 3 4 0 3 4 1 3 2
42  42  73.177965        10    5 5 4 4 1 5 0 0 4
43  43  50.912738        17      1 4 0 2 1 5 2 3
44  44  38.537445         9            4 3 1 2 5
45  45  63.285269        22    0 4 3 5 1 0 4 0 3
46  46  51.736054        29    2 2 3 3 2 0 2 5 3
47  47   9.394129         5                  2 1
48  48  46.913707        44    2 3 0 5 2 2 1 1 2
49  49   6.490396        58                    1

In [24]:
#Tipus de dades del DataFrame merged 'df_merged'
df_merged.dtypes

id            int64
euros       float64
customer      int64
products     object
dtype: object

In [25]:
#Crear nou DataFrame 'customer_ranking' amb les columnes 'id', 'firstname', 'lastname', 'total_euros'.
customer_ranking = pd.DataFrame(columns=["id", "firstname", "lastname", "total_euros"])

#Copiar dades 'id', 'firstname' i 'lastname' del DataFrame 'customers' a 'customer_ranking'
#NOTA: 'total_euros' encara no te cap valor.
customer_ranking["id"] = customers['id']
customer_ranking["firstname"] = customers['firstname']
customer_ranking["lastname"] = customers['lastname']

customer_ranking

    id firstname    lastname total_euros
0    0      John     Maxwell         NaN
1    1      John  Heisenberg         NaN
2    2      John       Fermi         NaN
3    3      John     Feynman         NaN
4    4      John   Lavoisier         NaN
5    5      John     Pasteur         NaN
6    6     James     Maxwell         NaN
7    7     James  Heisenberg         NaN
8    8     James       Fermi         NaN
9    9     James     Feynman         NaN
10  10     James   Lavoisier         NaN
11  11     James     Pasteur         NaN
12  12     Peter     Maxwell         NaN
13  13     Peter  Heisenberg         NaN
14  14     Peter       Fermi         NaN
15  15     Peter     Feynman         NaN
16  16     Peter   Lavoisier         NaN
17  17     Peter     Pasteur         NaN
18  18      Paul     Maxwell         NaN
19  19      Paul  Heisenberg         NaN
20  20      Paul       Fermi         NaN
21  21      Paul     Feynman         NaN
22  22      Paul   Lavoisier         NaN
23  23      Paul     Pasteur         NaN
24  24     Ringo     Maxwell         NaN
25  25     Ringo  Heisenberg         NaN
26  26     Ringo       Fermi         NaN
27  27     Ringo     Feynman         NaN
28  28     Ringo   Lavoisier         NaN
29  29     Ringo     Pasteur         NaN
30  30    Samuel     Maxwell         NaN
31  31    Samuel  Heisenberg         NaN
32  32    Samuel       Fermi         NaN
33  33    Samuel     Feynman         NaN
34  34    Samuel   Lavoisier         NaN
35  35    Samuel     Pasteur         NaN
36  36       Sam     Maxwell         NaN
37  37       Sam  Heisenberg         NaN
38  38       Sam       Fermi         NaN
39  39       Sam     Feynman         NaN
40  40       Sam   Lavoisier         NaN
41  41       Sam     Pasteur         NaN
42  42      Mary     Maxwell         NaN
43  43      Mary  Heisenberg         NaN
44  44      Mary       Fermi         NaN
45  45      Mary     Feynman         NaN
46  46      Mary   Lavoisier         NaN
47  47      Mary     Pasteur         NaN
48  48     Sarah     Maxwell         NaN
49  49     Sarah  Heisenberg         NaN
50  50     Sarah       Fermi         NaN
51  51     Sarah     Feynman         NaN
52  52     Sarah   Lavoisier         NaN
53  53     Sarah     Pasteur         NaN
54  54      Jane     Maxwell         NaN
55  55      Jane  Heisenberg         NaN
56  56      Jane       Fermi         NaN
57  57      Jane     Feynman         NaN
58  58      Jane   Lavoisier         NaN
59  59      Jane     Pasteur         NaN

In [26]:
#Tipus de dades del DataFrame 'customer_ranking'
customer_ranking.dtypes

id              int64
firstname      object
lastname       object
total_euros    object
dtype: object

In [ ]:
#For loop en el DataFrame 'customer_ranking'
for index_customer_ranking, row_product_customer in customer_ranking.iterrows():    
    res = 0
    #For loop en el DataFrame 'df_merged'.
    for index_orders, row_orders in df_merged.iterrows():
        if customer_ranking['id'][index_customer_ranking] == df_merged['customer'][index_orders]:
            res += df_merged['euros'][index_orders]

    #Guardar resultat del total_euros que el client ha gastat en productes.
    customer_ranking.loc[index_customer_ranking, 'total_euros'] = res

#Ordenar les columnes de forma descendent pel camp 'total_euros'.
customer_ranking = customer_ranking.sort_values(by="total_euros", ascending=False)
customer_ranking

    id firstname    lastname total_euros
34  34    Samuel   Lavoisier  145.254336
44  44      Mary       Fermi  138.410627
24  24     Ringo     Maxwell   136.82767
22  22      Paul   Lavoisier   124.71069
32  32    Samuel       Fermi  119.163897
5    5      John     Pasteur   99.143736
10  10     James   Lavoisier   73.177965
29  29     Ringo     Pasteur   70.031752
38  38       Sam       Fermi   65.070853
41  41       Sam     Pasteur   60.777999
21  21      Paul     Feynman   54.641202
15  15     Peter     Feynman   54.270757
59  59      Jane     Pasteur   52.642395
50  50     Sarah       Fermi   51.168289
17  17     Peter     Pasteur   50.912738
28  28     Ringo   Lavoisier   45.540896
3    3      John     Feynman   40.341694
9    9     James     Feynman   38.537445
47  47      Mary     Pasteur   38.279942
37  37       Sam  Heisenberg   37.190652
46  46      Mary   Lavoisier   36.668828
45  45      Mary     Feynman   35.791337
51  51     Sarah     Feynman    34.59259
20  20      Paul       Fermi   34.399455
19  19      Paul  Heisenberg   33.658163
54  54      Jane     Maxwell   28.202881
57  57      Jane     Feynman   23.145479
6    6     James     Maxwell   22.810544
25  25     Ringo  Heisenberg   20.870504
0    0      John     Maxwell    18.94312
35  35    Samuel     Pasteur   16.296891
40  40       Sam   Lavoisier   15.356456
8    8     James       Fermi   12.710227
36  36       Sam     Maxwell    9.806495
58  58      Jane   Lavoisier    6.490396
48  48     Sarah     Maxwell    5.884896
1    1      John  Heisenberg           0
11  11     James     Pasteur           0
2    2      John       Fermi           0
56  56      Jane       Fermi           0
55  55      Jane  Heisenberg           0
4    4      John   Lavoisier           0
53  53     Sarah     Pasteur           0
52  52     Sarah   Lavoisier           0
7    7     James  Heisenberg           0
49  49     Sarah  Heisenberg           0
13  13     Peter  Heisenberg           0
12  12     Peter     Maxwell           0
31  31    Samuel  Heisenberg           0
14  14     Peter       Fermi           0
43  43      Mary  Heisenberg           0
42  42      Mary     Maxwell           0
16  16     Peter   Lavoisier           0
39  39       Sam     Feynman           0
18  18      Paul     Maxwell           0
23  23      Paul     Pasteur           0
26  26     Ringo       Fermi           0
33  33    Samuel     Feynman           0
27  27     Ringo     Feynman           0
30  30    Samuel     Maxwell           0

In [28]:
#Exportar el DataFrame en un fitxer CSV (customer_ranking.csv)
customer_ranking.to_csv("customer_ranking.csv", index=False)